# Generated by Django 3.1.1 on 2020-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_plant_amount_of_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='amount_of_water',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='low', max_length=10),
        ),
    ]
