# Generated by Django 3.1.1 on 2020-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0004_plant_worth_buying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='amount_of_light',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='amount_of_water',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=10),
        ),
    ]
