# Generated by Django 3.1.1 on 2020-11-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0005_auto_20201109_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='L', max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_app.plant')),
            ],
        ),
    ]
